   
    <?php if(isset($this->_data['error'])){?>
    	<p class="text-error"><?php echo $this->_data['error']?></p>
    <?php } ?>
    
    <form class="form-horizontal" name="FormUser" action="index.php?controller=User&action=Login" method="POST">
	    <div class="control-group">
		    <label class="control-label" for="inputLogin">Login</label>
		    <div class="controls">
			    <input type="text" id="inputLogin" name="inputLogin" placeholder="Login">
			</div>
		 </div>
		 <div class="control-group">
		    <label class="control-label" for="inputPassword">Password</label>
		    <div class="controls">
		    <input type="password" id="inputPassword" name="inputPassword" placeholder="Password">
		    </div>
		 </div>
		 <div class="control-group">
		    <div class="controls">
		    	<label class="checkbox">
		    		<input type="checkbox"> Remember me
		    	</label>
		    <button type="submit" class="btn" name="valider">Se Connecter</button>
		 </div>
	    </div>
    </form>