 <?php 
 if(User::isConnected()){?>
 
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mon Compte <span class="badge"></span> <b class="caret"></b></a>
    <ul class="dropdown-menu">
		<li><a href="index.php?controller=User&action=Details"><?php echo User::getInstance()->getLogin()?> (Details)</a></li>
		<li><a href="index.php?controller=Commande">Mes Commandes</a></li>
		<li role="presentation" class="divider"></li>
		<li><a href="index.php?controller=User&action=Disconnect">Se Deconnecter</a></li>
    </ul>
   </li>
 <?php 
 }
 else {
?>
 	  <li>
	 	<a href="index.php?controller=User&action=Form">Connexion</a>
	 </li>
 <?php }?>