<h1>Mes commandes</h1>

	
<table class="table table-hover">
	<thead>
		<tr>
			<th>id</th>
			<th>date</th>
			<th>Montant total</th>
		</tr>
	</thead>
	<tbody>
<?php foreach($this->_data['lescommandes']->getAll() as $lacommande){?>
	<tr>
		<td><?php echo $lacommande->get_id() ?></td>
		<td><?php echo $lacommande->get_datecommande() ?></td>
		<td><?php echo $lacommande->get_montantHT() ?></td>
	</tr>
<?php } ?>
	</tbody>
</table>

 