<h2>Bienvenu sur l'application Lafleur 2013</h2>
<p>
	Cette application web écrite en PHP est déstinée à un usage pédagogique uniquement.
</p>
<p>
	L'application repose sur un Framework minimaliste permettant l'implémentation du patron de conception (Design Pattern) Model Vue Controller, plus communément appelé MVC. <br/>
	Le framework propose aussi l'utilisation d'une couche très simpliste d'ORM (Objet Relational Mapping) ou gestion de la persistence des objet au sein d'un SGBD. Son implémentation ne propse que l'automatisation des opérations de Lecture (Read dans le modèle CRUD Create Read Update Delete). L'implémentation des opération de Création (Insert en SQL) est de la responsabilité du developpeur.
</p>
<p>
	<h3>PedaFramework</h3>
	<ul>
		<li>MVC</li>
		<li>ORM</li>
	</ul>
</p>
